### ISSUE TITLE
Issue with deployment.

### ISSUE THREAD

**Issue by Keshav-Madhav** [dgreenheck/minecraft-threejs-clone#16]
Hello Dan!!

I have just completed your Minecraft ThreeJS Clone follow along. I now wish to deploy it similar to how you have done it. I tried to do it and it is giving errors. Can you provide me steps or guide me on how do i publish it?
Thanks a lot!

**Comment by Keshav-Madhav** [comment]
I forgot to mention. I developed in typescript while following along with you. If that is the reason my deployment using github pages could be broken, can you clarify that aswell. Thanks!

**Comment by AerixBlox1** [comment]
You can host it using replit, what I did is fork the repository and imported it from github to my replit then you can run it and use deployments to keep it online (its a 99.89% chance it will be online) but its pretty 24/7

**Comment by dgreenheck** [comment]
@Keshav-Madhav I can't tell you what is wrong with your deployment without seeing the errors. I use GitHub Actions to build my site and deploy it. Here is the YAML code for doing so. You can't host it directly because you need to bundle Three.js with your app, and in your case, transpile TS into JS.

I would recommend reading the GitHub pages documentation to learn how to customize this script for your repository.

```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
